name: Dockerfile Base Image Updater
description: Updates base images inside dockerfiles.
author: piotrekkr

inputs:
  dockerfile:
    description: Dockerfile path
    required: true

runs:
  using: node20
  main: dist/index.js
