name: Dockerfile Updater
description: Update base images in Dockerfile
author: piotrekkr

inputs:
  dockerfile:
    description: Dockerfile path
    required: true

runs:
  using: node20
  main: dist/index.js
