title = "Gitleaks configuration"

[extend]
useDefault = true

[allowlist]
description = "Ignore dummy example auth"
regexes = [
  '''dXNlcjpwYXNzCg=='''
]
#paths = [
#  '''__tests__/docker.test.js'''
#]